### ISSUE TITLE
[Bug]: Dart filenames

### ISSUE THREAD

**Issue by Khaoz-Topsy** [AssistantNMS/App#105]
### Describe the bug

The filenames are inconsistent and according to Effective Dart style, they should be lowercase_with_underscores

### To Reproduce

All the `.dart` files

### Expected behavior

Should be lowercase_with_underscores

### Where did you find this problem?

Android

**Comment by Lenni009** [comment]
In the "constants" folder, filenames begin with a capital letter. Should that be preserved or also converted to all lowercase? E.g. does "AlienPuzzle.dart" become "Alien_puzzle.dart" or "alien_puzzle.dart"?

**Comment by Lenni009** [comment]
List of folders to convert:

- [ ] /lib/
- [ ] components/adaptive
- [ ] components/common
- [ ] components/dialogs
- [ ] components/floatingActionButton
- [ ] components/guide
- [ ] components/modalBottomSheet
- [ ] components/portal
- [ ] components/scaffoldTemplates
- [ ] components/tilePresenters
- [ ] ./components/
- [ ] ./constants/
- [ ] ./contracts/
- [ ] contracts/alienPuzzle
- [ ] contracts/auth
- [ ] contracts/cart
- [ ] contracts/creature
- [ ] contracts/data
- [ ] contracts/enum
- [ ] contracts/faction
- [ ] contracts/favourite
- [ ] contracts/generated
- [ ] contracts/guide
- [ ] contracts/helloGames
- [ ] contracts/inventory
- [ ] contracts/journey
- [ ] contracts/misc
- [ ] contracts/nsmfm
- [ ] contracts/portal
- [ ] contracts/redux
- [ ] contracts/search
- [ ] contracts/seasonalExpedition
- [ ] contracts/techTree
- [ ] contracts/timer
- [ ] contracts/twitch
- [ ] ./env/
- [ ] ./helpers/
- [ ] ./integration/
- [ ] ./mapper/
- [ ] ./pages/
- [ ] pages/alienPuzzles
- [ ] pages/catalogue
- [ ] pages/community
- [ ] pages/contributors
- [ ] pages/faction
- [ ] pages/favourite
- [ ] pages/friendCode
- [ ] pages/generic
- [ ] pages/guide
- [ ] pages/helloGames
- [ ] pages/homepage
- [ ] pages/inventory
- [ ] pages/ios
- [ ] pages/misc
- [ ] pages/neItemsInUpdate
- [ ] pages/news
- [ ] pages/nmsfm
- [ ] pages/portal
- [ ] pages/power
- [ ] pages/seasonalExpedition
- [ ] pages/social
- [ ] pages/special
- [ ] pages/sync
- [ ] pages/techTree
- [ ] pages/timer
- [ ] pages/title
- [ ] pages/tutorial
- [ ] pages/whatIsNew
- [ ] ./redux/middleware
- [ ] ./redux/modules
- [ ] modules/base
- [ ] modules/cart
- [ ] modules/expedition
- [ ] modules/favourite
- [ ] modules/generic
- [ ] modules/inventory
- [ ] modules/journeyMilestone
- [ ] modules/portal
- [ ] modules/setting
- [ ] modules/timer
- [ ] modules/titles
- [ ] modules/viewModel
- [ ] ./services/api
- [ ] services/base
- [ ] base/interface
- [ ] services/json
- [ ] json/interface
- [ ] ./theme/
- [ ] ./validation/

**Comment by Khaoz-Topsy** [comment]
All lowercase, it is a good time to do this. The `develop` branch is very different to master now because of some migrations I have started like this commit https://github.com/AssistantNMS/App/commit/b611c01a3b5a2e10b1ec0e144063ed2bae02757b 😝

**Comment by Lenni009** [comment]
yeah I saw that null safety stuff in Flutter 3 and wondered if you already implemented it

**Comment by Lenni009** [comment]
should folders like lib/components/floatingActionButton/ also be converted to floating_action_button or should they stay camelCase?

**Comment by Khaoz-Topsy** [comment]
I am pretty sure that folders can be left alone 😋 
If you edit this file https://github.com/AssistantNMS/App/blob/develop/analysis_options.yaml and remove the rules section, your VSCode should start showing warnings, might need a Flutter extension 🤔
