### ISSUE TITLE
[Bug]: Switch friend code validation

### ISSUE THREAD

**Issue by Khaoz-Topsy** [AssistantNMS/App#135]
### Describe the bug

Switch friend codes start with `SW-`

### To Reproduce

1. Go to 'Friends code' page
2. Click on add
3. Try supplying a Switch friends code

### Expected behavior

On Sswitch it should require the `SW-` or at least display it as a mask

### Where did you find this problem?

Android, iOS

### Additional context

In the image below, entering `SW-8176-2200-5633` should be possible

![image](https://user-images.githubusercontent.com/15005470/200355342-62699db1-0050-4867-8713-41e6cba0d1ef.png)

**Comment by Khaoz-Topsy** [comment]
Plz confirm @cyberpunk2350

**Comment by cyberpunk2350** [comment]
@Khaoz-Topsy can confirm that SW friend code format is SW-####-####-####
I can also confirm that at the moment there are no options to display your NMS Friend Code on this SW version.
I would recommend that you add a note that this FC is console level and not game level and that the SW version of the game doesn't support MP/Friend Codes
or something to that point
