### ISSUE TITLE
[Bug]: Duplicate "Orbital Exocraft Materializer"

### ISSUE THREAD

**Issue by Khaoz-Topsy** [AssistantNMS/App#153]
### Describe the bug

There are two entries for "Orbital Exocraft Materializer"

<table>
  <tr>
    <th>
    build395
    </th>
    <th>
    build884
    </th>
  </tr>
  <tr>
    <td>
      <img src="https://user-images.githubusercontent.com/15005470/207044509-2a10db5e-7d19-410b-af92-e423f083234c.png" width="250px"/>
    </td>    
    <td>
      <img src="https://user-images.githubusercontent.com/15005470/207044532-9b3a1a17-8a20-40e9-a644-e206ce0459fd.png" width="250px"/>
    </td>
  </tr>
</table>

### To Reproduce

1. Go to 'All items' page
2. Search for "Orbital Exocraft Materializer"

### Expected behavior

The older one should be removed

### Where did you find this problem?

Android, iOS, Windows, WebApp

**Comment by cyberpunk2350** [comment]
Should it be removed or just maked deprecated? Because it can still sow up in Legacy saves, and for anyone running older versions of the game.

**Comment by Khaoz-Topsy** [comment]
I was going to remove it from the apps entirely, but when I ran the data mining program it complained that it is a reward in one of the expeditions, so I am just going to mark it as "obsolete" like the Wooden Wall 😋. You make an extra good point because it could also be in an inventory from someone's NomNom sync 🤔   

![image](https://user-images.githubusercontent.com/15005470/207044013-b7df70f7-5924-4002-b960-7f3827c333d9.png)
