### ISSUE TITLE
[Bug]: Screen goes black when changing homepage style

### ISSUE THREAD

**Issue by Lenni009** [AssistantNMS/App#158]
### Describe the bug

The screen turns black when changing homepage style.

### To Reproduce

1. Go to settings.
2. Change default homepage.
3. Screen goes black until you restart the app.

### Expected behavior

Screen shouldn't turn black, but instead just show the settings menu with your changed option

### Where did you find this problem?

Android

### Logs

Logs seem to clear on app restart -> can't provide any

### Additional context

Tested on a Huawei Mate 20 Pro running EMUI 12 (Android 10).
App version: 2.6.0.

**Comment by Khaoz-Topsy** [comment]
A very annoying bug, the navigation service was popping 1 too many times: [this commit solves the issue](https://github.com/AssistantApps/Flutter.Common/commit/14e41d7b299bba846ca2d8ac2d631b7c57315cd9).

Thank you for creating this issue and for all the bug hunting you do! I hope you enjoy being issued the very first Holopin 😋 . Hopefully it works first time 🤞 
@holopin-bot @Lenni009 bug-finder

**Comment by Khaoz-Topsy** [comment]
@holopin-bot @Lenni009

**Comment by Lenni009** [comment]
Try again

**Comment by Khaoz-Topsy** [comment]
Looks like it was my bad config 😝
@holopin-bot @Lenni009 bug-finder
