### ISSUE TITLE
[Bug]: Incorrect prices for certain items

### ISSUE THREAD

**Issue by Lenni009** [AssistantNMS/App#162]
### Describe the bug

Certain items (for example Storm Crystal, Crystal Sulphide, Hadal Core) have incorrect unit values in the app.

### To Reproduce

1. Go into gamefiles -> PRODUCTTABLE -> VENTGEM -> BaseValue: 7800
2. Go to 'Crystal Sulphide' item page
3. See price is 7800 (like game files)
4. Go into game, look at Crystal Sulphide price: 7410

### Expected behavior

Display the price from the game (7410). This also applies to other items as mentioned.

To achieve this, we need to make the following assumption:
LowPriceMod and HighPriceMod influence the price (this is a fact).
0.1 stands for 5% price (I don't have any data evidence beyond manual observations)

So if we have a BaseValue of 100, and a HighPriceMod of 0.1, the game displays a price of 105.
If the HighPriceMod was -0.05, the game would display 97 (-2.5u, game rounds down)

The same is true for LowPriceMod.

The two can also be combined:
Let's say we have HPM of 0.1 and LPM of -0.1, they cancel each other out and we get the BaseValue in the game.
If you have one with -0.1 and one with 0.2, they result in 0.1, giving a +5% price.
This means that they just get added together before calculating the price:

```
var baseValue = 1000;
var HPM = -0.1;
var LPM = 0.2;

var percentage= (LPM + HPM) * 0.5;

var modifier = baseValue * percentage;

var result = baseValue + modifier;

console.log(Math.floor(result)); // 1050
```

Substance, Product and Tech tables have these values, but for tech they are all 0.

Another example with Crystal Sulphide using the real world game file values:
```
var baseValue = 7800;
var HPM = -0.1;
var LPM = 0;

var percentage= (LPM + HPM) * 0.5;

var modifier = baseValue * percentage;

var result = baseValue + modifier;

console.log(Math.floor(result)); // 7410
```

### Where did you find this problem?

Android, WebApp

### Additional context

This is the result of the investigation started in the Crystal Sulphide Datamining Discord Thread

**Comment by Khaoz-Topsy** [comment]
Here are some of the items that had their values changed 😋

// Curiosities
Larval Core
Living Pearl
Hypnotic Eye
Hadal Core
Storm Crystal
Albumen Pearl
Gravitino Ball
Sac Venom
Geode (Curiosity)
Crystal Fragment
Tritium Hypercluster
Gold Nugget
Crystal Sulphide
Anomaly Detector
Emergency Signal Scanner
Emergency Signal Scanner (Active)
Freighter Recolouring
Glowing Mineral
Sentinel Flare (Off)

// Products
Suspicious Packet (Goods)
Suspicious Packet (Tech)
Suspicious Packet (Arms)
Geode (Product)
Undamaged Drone Shell
Nanite Filament
Portal Phylactery
Beads of Glass
Sentinel Flare
Deep-Space Lure

// RawMaterials
Nanite Cluster
QUICKSILVER
UNITS

**Comment by Lenni009** [comment]
You forgot to round down. Game says 358, you say 358.8
![grafik](https://user-images.githubusercontent.com/91371655/214651763-51867249-c1e9-4178-82cf-76b8dbe1cd63.png)
![grafik](https://user-images.githubusercontent.com/91371655/214651789-218b9231-4161-47f2-af20-a699a9eddb32.png)

**Comment by Khaoz-Topsy** [comment]
Agh, I did round but to one decimal 😂
