### ISSUE TITLE
🚀 Feature request: change Hamburger menu on the bottom right of item pages 

### ISSUE THREAD

**Issue by Lenni009** [AssistantNMS/App#181]
### 🔖 Describe the solution you'd like

Turn the Hamburger menu on the bottom right of item pages  into a `+` sign, since it's there to add stuff to cart or inventory 

### 👀 Have you checked if this bug report has been created already?

- [X] I checked and couldn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/AssistantNMS/App/blob/main/.github/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Lenni009** [comment]
Now that this is implemented, can the `+` rotate to an `x` when clicked?

**Comment by Khaoz-Topsy** [comment]
Unfortunately the library doesn't have an icon for that scenario... Here are some built in options available [https://api.flutter.dev/flutter/material/AnimatedIcons-class.html#material.AnimatedIcons.1](https://api.flutter.dev/flutter/material/AnimatedIcons-class.html#material.AnimatedIcons.1) I was going to do a simple rotate 45 degrees when open, but the isOpen state is somewhere within the SpeedDial package that I can't reach, so I would have to create an animation tween thingy. And I don't wanna do that 😂
