### ISSUE TITLE
🐛 Bug Report: Spawn animations play when they shouldn't

### ISSUE THREAD

**Issue by Lenni009** [AssistantNMS/App#191]
### 📜 Describe the bug

"Maximum Stack", price and recipe required item numbers animate when they enter the viewport, rather than just on pageload/first view.

### 👟 To Reproduce

1. Go to "Carbon" page
2. Scroll down to the bottom
3. Scroll back up to the top
4. See the "Maximum Stack" and price elements scale up again as their spawn animation

5. Go back to bottom
6. See required item numbers play their animation as well

### 👍 Expected behavior

Only play animation once when they enter the viewport, block subsequent animations.

### 📱 Where did you find this problem?

Android

### 👀 Have you checked if this bug report has been created already?

- [X] I checked and couldn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/AssistantNMS/App/blob/main/.github/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Khaoz-Topsy** [comment]
I actually prefer it this way, makes the pages more lively 🤔
