### ISSUE TITLE
🐛 Bug Report: App reports wrong version

### ISSUE THREAD

**Issue by Lenni009** [AssistantNMS/App#192]
### 📜 Describe the bug

App reported app version as 2.8.1 when it should be 2.9.0.

Especially weird because the code has no "2.8.1" references

### 👟 To Reproduce

1. Open sidebar
2. scroll down
3. See "App version" saying 2.8.1

### 👍 Expected behavior

Should show correct version (2.9.0)

### 📱 Where did you find this problem?

Android

### 👀 Have you checked if this bug report has been created already?

- [X] I checked and couldn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/AssistantNMS/App/blob/main/.github/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Khaoz-Topsy** [comment]
This was due to me not running the version number script before pushing the update 😅. I added it to the build step, so hopefully I won't need to run it manually, we will have to see if it works on the next push to prod 😋
