### ISSUE TITLE
🚀 Feature request: Add notice to NomNom Sync page that this feature only works on PC

### ISSUE THREAD

**Issue by Lenni009** [AssistantNMS/App#249]
### 🔖 Describe the solution you'd like

It should be made clear that the NomNom sync does only work with a PC.

I had someone ask how to do it on PS5, and they were disappointed when they learned they couldn't use the feature.

### 👀 Have you checked if this bug report has been created already?

- [X] I checked and couldn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/AssistantNMS/App/blob/main/.github/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Khaoz-Topsy** [comment]
Only supported on PC is mentioned 😋 
![image](https://github.com/AssistantNMS/App/assets/15005470/31d7756d-1ff3-4cbd-a466-f9dc8508a344)
