### ISSUE TITLE
Track your cooking Catalogue

### ISSUE THREAD

**Issue by Khaoz-Topsy** [AssistantNMS/App#4]
**Describe the solution you'd like**
Like a listing of them in the order displayed in the catalogue and you can mark off the ones you've done and look up the recipes for the ones you need still.

### Preparation: 
- [x] Find out if we can grab the order of cooking items that the game displays them in, then document here

METADATA/REALITY/CATALOGUEMATERIALS.MBIN

CategoryID: `UI_PORTAL_CAT_MAT_COOK` -> `Items`

### Actual Dev:
- [ ] Page to view all cooking items
  - [ ] Icon for page (must be in the secondary like the other icons)
  - [ ] Colour images for complete
  - [ ] Greyscale images for incomplete
- [ ] Add setting on Settings page, to turn on a note when item has not been cooked
- [ ] On Item detail page show a tile when an item has not been completed

**Comment by Lenni009** [comment]
The full ingame cooking catalogue for reference: https://nomanssky.fandom.com/wiki/Catalogue#Cooking

The order of items in the game files does not match what we see in game.

**Comment by Lenni009** [comment]
These pictures were taken at 1080p, we should also investigate if screen resolution plays a role in how many items are displayed per page

**Comment by Lenni009** [comment]
I can't make out a pattern in the first three items 😐

They are not sorted alphabetically, not sorted by value, not sorted by cooking value, not sorted alphabetically by ID...

**Comment by Lenni009** [comment]
@Khaoz-Topsy I got it:

METADATA/REALITY/CATALOGUEMATERIALS.MBIN

CategoryID: `UI_PORTAL_CAT_MAT_COOK`

**Comment by Khaoz-Topsy** [comment]
@Lenni009 you genius 🧠
Now to figure out how to display this in the apps, can't really do the same grid 🤔 
Maybe we keep this as a WebApp only feature 🤔

**Comment by Lenni009** [comment]
But how would the presentation on web differ from the presentation on mobile? It would be a grid either way, wouldn't it? Or maybe a list on mobile, like we have for titles?

**Comment by Lenni009** [comment]
Couldn't we possibly generate the silhouette images from the normal images, by simply making a mask with the alpha channel and filling it with black?

**Comment by Khaoz-Topsy** [comment]
On the web I can display 7 or 8 columns easily, on mobile that would look really bad. A list is pretty much the only way we could do it on mobile, but I imagine that it wont be as useful for someone looking for an item they are missing. Since you can't go to a specific page or look at the column and row on your game catalogue and match it with the list

The silhouette shouldn't be a problem 😋

**Comment by Lenni009** [comment]
As I have shown in a previous screenshot, the number of columns varies with screen width anyway, so it makes no sense to rebuild the exact UI

**Comment by Lenni009** [comment]
Of course we could try some trickery to get 7 columns at 720p, 8 columns at 1080p, and however many you get at 4k. But not everyone is in full screen browser, and this is very hacky and not really good

**Comment by Khaoz-Topsy** [comment]
Well I wouldn't call it hacky, since adjusting the number of columns based on screen size is called responsive design 😉

**Comment by Lenni009** [comment]
WQHD has same layout as Full HD:

![WQHD](https://media.discordapp.net/attachments/812176492183289860/1076457317433876500/20230218115651_1.jpg)

**Comment by Lenni009** [comment]
Do you have a UHD screen? If yes, could you test it on that resolution? I guess it'll also be 8x4, but let's make sure

**Comment by Lenni009** [comment]
Also note that not all people play on PC. Some console people might have a 4k TV, but only a 1080p PC screen. I'll have someone check it out as well later.

**Comment by Lenni009** [comment]
UDH also uses 8x4:

![UHD](https://cdn.discordapp.com/attachments/812176492183289860/1076476282625327254/image.png)
